# Dataset Financial Question and Answer

In [1]:
import pandas as pd

df = pd.read_parquet("hf://datasets/FinGPT/fingpt-fiqa_qa/data/train-00000-of-00001-ab79bf9300210e98.parquet")

In [2]:
df.columns

Index(['input', 'output', 'instruction'], dtype='str')

In [3]:
df.shape

(17110, 3)

In [4]:
df.head()

,input,output,instruction
0,What is considered a business expense on a bus...,The IRS Guidance pertaining to the subject. I...,"Utilize your financial knowledge, give your an..."
1,Claiming business expenses for a business with...,Yes you can claim your business deductions if ...,Offer your insights or judgment on the input f...
2,Transferring money from One business checking ...,You should have separate files for each of the...,"Based on your financial expertise, provide you..."
3,Having a separate bank account for business/in...,Having a separate checking account for the bus...,Share your insights or perspective on the fina...
4,Having a separate bank account for business/in...,"You don't specify which country you are in, so...",Offer your thoughts or opinion on the input fi...

## Samples

In [5]:
index = 0
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  What is considered a business expense on a business trip?
output:  The IRS Guidance pertaining to the subject.  In general the best I can say is your business expense may be deductible.  But it depends on the circumstances and what it is you want to deduct. Travel Taxpayers who travel away from home on business may deduct related   expenses, including the cost of reaching their destination, the cost   of lodging and meals and other ordinary and necessary expenses.   Taxpayers are considered “traveling away from home” if their duties   require them to be away from home substantially longer than an   ordinary day’s work and they need to sleep or rest to meet the demands   of their work. The actual cost of meals and incidental expenses may be   deducted or the taxpayer may use a standard meal allowance and reduced   record keeping requirements. Regardless of the method used, meal   deductions are generally limited to 50 percent as stated earlier.    Only actual costs for lodging may be claimed as an expense and   receipts must be kept for documentation. Expenses must be reasonable   and appropriate; deductions for extravagant expenses are not   allowable. More information is available in Publication 463, Travel,   Entertainment, Gift, and Car Expenses. Entertainment Expenses for entertaining clients, customers or employees may be   deducted if they are both ordinary and necessary and meet one of the   following tests: Directly-related test: The main purpose of the entertainment activity is the conduct of business, business was actually conducted   during the activity and the taxpayer had more than a general   expectation of getting income or some other specific business benefit   at some future time.   Associated test: The entertainment was associated with the active conduct of the taxpayer’s trade or business and occurred directly   before or after a substantial business discussion. Publication 463 provides more extensive explanation of these tests as   well as other limitations and requirements for deducting entertainment   expenses. Gifts Taxpayers may deduct some or all of the cost of gifts given in the   course of their trade or business. In general, the deduction is   limited to $25 for gifts given directly or indirectly to any one   person during the tax year. More discussion of the rules and   limitations can be found in Publication 463. If your LLC reimburses you for expenses outside of this guidance it should be treated as Income for tax purposes. Edit for Meal Expenses: Amount of standard meal allowance.   The standard meal allowance is   the federal M&IE rate. For travel in 2010, the rate for most small   localities in the United States is $46 a day. Source IRS P463 Alternately you could reimburse at a per diem rate
instruction:  Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.

In [6]:
index = 1
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  Claiming business expenses for a business with no income
output:  Yes you can claim your business deductions if you are not making any income yet. But first you should decide what structure you want to have for your business. Either a Company structure or a Sole Trader or Partnership. Company Structure If you choose a Company Structure (which is more expensive to set up) you would claim your deductions but no income. So you would be making a loss, and continue making losses until your income from the business exceed your expenses. So these losses will remain inside the Company and can be carried forward to future income years when you are making profits to offset these profits. Refer to ATO - Company tax losses for more information. Sole Trader of Partnership Structure If you choose to be a Sole Trader or a Partnership and your business makes a loss you must check the non-commercial loss rules to see if you can offset the loss against your income from other sources, such as wages. In order to offset your business losses against your other income your business must  pass one of these tests: If you don't pass any of these tests, which being a start-up you most likely won't, you must carry forward your business losses until an income year in which you do pass one of the tests, then you can offset it against your other income. This is what differentiates a legitimate business from someone having a hobby, because unless you start making at least $20,000 in sales income (the easiest test to pass) you cannot use your business losses against your other income. Refer to ATO - Non-commercial losses for more information.
instruction:  Offer your insights or judgment on the input financial query or topic using your financial expertise. Reply as normal question answering

In [7]:
index = 100
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  How can I lookup the business associated with a FEIN?
output:  If the organization is a non-profit. You can search by EIN on Charity Navigator's website FOR FREE. https://www.charitynavigator.org/
instruction:  Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.

## Missing data?

In [8]:
df.notna().sum()

input          17110
output         17110
instruction    17110
dtype: int64

In [9]:
df.isnull().sum()

input          0
output         0
instruction    0
dtype: int64

In [10]:
df.isna().sum()

input          0
output         0
instruction    0
dtype: int64

In [11]:
((df == "") | (df == " ")).sum()

input          0
output         0
instruction    0
dtype: int64

In [12]:
for column in df.columns: 
    print(df[column].str.match(r'^\s*$').sum())

0
0
0

No missing values!

In [13]:
df.describe()

,input,output,instruction
count,17110,17110,17110
unique,6648,17071,5
top,"What options do I have at 26 years old, with 1...",nan,"Utilize your financial knowledge, give your an..."
freq,23,38,3422

There are 5 types of instructions:

In [14]:
for i, prompt in enumerate(df.instruction.unique()):
    print(f"Prompt {i}:", prompt, "\n\n")

Prompt 0: Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.


Prompt 1: Offer your insights or judgment on the input financial query or topic using your financial expertise. Reply as normal question answering


Prompt 2: Based on your financial expertise, provide your response or viewpoint on the given financial question or topic. The response format is open.


Prompt 3: Share your insights or perspective on the financial matter presented in the input.


Prompt 4: Offer your thoughts or opinion on the input financial query or topic using your financial background.

# Dataset: S&P 500 SEC Fillings

To understand each of the items go to the [wiki page](https://en.wikipedia.org/wiki/Form_10-K).

How to directly extract from the [sec api](https://sec-api.io/docs/sec-filings-item-extraction-api/python-example).

In [2]:
from datasets import load_dataset

ds = load_dataset("jlohding/sp500-edgar-10k")

data/2013.parquet:   0%|          | 0.00/71.6M [00:00<?, ?B/s]

data/2014.parquet:   0%|          | 0.00/72.9M [00:00<?, ?B/s]

data/2015.parquet:   0%|          | 0.00/72.2M [00:00<?, ?B/s]

data/2016.parquet:   0%|          | 0.00/74.6M [00:00<?, ?B/s]

data/2017.parquet:   0%|          | 0.00/74.8M [00:00<?, ?B/s]

data/2018.parquet:   0%|          | 0.00/76.7M [00:00<?, ?B/s]

data/2019.parquet:   0%|          | 0.00/76.9M [00:00<?, ?B/s]

data/2020.parquet:   0%|          | 0.00/75.6M [00:00<?, ?B/s]

data/2021.parquet:   0%|          | 0.00/80.2M [00:00<?, ?B/s]

data/2022.parquet:   0%|          | 0.00/79.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/6282 [00:00<?, ? examples/s]

In [6]:
df_train = ds["train"].to_pandas()

In [56]:
ds["train"]

Dataset({
    features: ['cik', 'sic', 'company', 'date', 'item_1', 'item_1A', 'item_1B', 'item_2', 'item_3', 'item_4', 'item_5', 'item_6', 'item_7', 'item_7A', 'item_8', 'item_9', 'item_9A', 'item_9B', 'item_10', 'item_11', 'item_12', 'item_13', 'item_14', 'item_15', 'ret', 'mkt_cap', '1_day_return', '3_day_return', '5_day_return', '10_day_return', '20_day_return', '40_day_return', '60_day_return', '80_day_return', '100_day_return', '150_day_return', '252_day_return', '__index_level_0__'],
    num_rows: 6282
})

In [8]:
df_train.columns

Index(['cik', 'sic', 'company', 'date', 'item_1', 'item_1A', 'item_1B',
       'item_2', 'item_3', 'item_4', 'item_5', 'item_6', 'item_7', 'item_7A',
       'item_8', 'item_9', 'item_9A', 'item_9B', 'item_10', 'item_11',
       'item_12', 'item_13', 'item_14', 'item_15', 'ret', 'mkt_cap',
       '1_day_return', '3_day_return', '5_day_return', '10_day_return',
       '20_day_return', '40_day_return', '60_day_return', '80_day_return',
       '100_day_return', '150_day_return', '252_day_return',
       '__index_level_0__'],
      dtype='str')

In [48]:
"western digital" in df_train["company"].str.lower()[10]

True

In [51]:
for index, word in enumerate(df_train["company"].str.lower()):
    
    if "western digital" in word:
        print(index)

10
815
1272
1778
1908
2809
3247
3471
4297
4788
4843
5726
6203

In [13]:
from IPython.display import Markdown, display
display(Markdown(df_train.item_1[0]))

Item 1. BUSINESS
Overview
C.H. Robinson Worldwide, Inc. (“C.H. Robinson,” “the company,” “we,” “us,” or “our”) is one of the largest third party logistics companies in the world with 2009 consolidated total revenues of $7.6 billion. We provide freight transportation services and logistics solutions to companies of all sizes, in a wide variety of industries. During 2009 we handled approximately 7.5 million shipments for more than 35,000 customers. We operate through a network of 235 offices, which we call branches, in North America, Europe, Asia, South America, Australia, and the Middle East. We have developed global multimodal transportation and distribution networks to provide logistics services worldwide. As a result, we have the capability of facilitating most aspects of the supply chain on behalf of our customers.
We do not own the transportation equipment that is used to transport our customers’ freight. Through our contractual relationships with approximately 47,000 transportation companies, including motor carriers, railroads (primarily intermodal service providers), air freight and ocean carriers, we select and hire the appropriate transportation to meet our customers’ freight needs. Because we rely on subcontractors to transport freight, we can be flexible and focus on seeking solutions that work for our customers, rather than focusing on asset utilization. As an integral part of our transportation services, we provide a wide range of value-added logistics services, such as supply chain analysis, freight consolidation, core carrier program management, and information reporting.
In addition to multimodal transportation services, we have two other services: fresh produce sourcing and fee-based information services.
Our Sourcing business is the buying, selling, and marketing of fresh produce. It was our original business when we were founded in 1905. Much of our logistics expertise can be traced to our significant experience in handling produce and perishable commodities. We purchase fresh produce through our network of independent produce suppliers. Our customers include regional and national grocery retailers and restaurants, produce wholesalers, and foodservice distributors. In many cases, we also arrange the transport of the fresh produce we sell through our contractual relationships with owners of specialized transportation equipment. We have developed our own brands of produce including The Fresh 1® and OurWorld® Organics, and we also have entered into licensing agreements to distribute produce under other national brand names. The produce for these brands is sourced through a preferred grower network and packed to order through contract packing agreements. We have instituted quality assurance and monitoring procedures as part of our Sourcing business.
Information Services is comprised of a C.H. Robinson subsidiary, T-Chek Systems, Inc., (T-Chek). T-Chek is a business-to-business provider of spend management and payment processing services. T-Chek’s customers are primarily motor carriers and truck stop chains. T-Chek’s platform supports open and closed loop networks that facilitate a variety of funds transfer, vendor payments, fuel purchasing, and online expense management.
Our business model has been the main driver of our historical results and has positioned us for continued growth. One of our competitive advantages is our branch network of 235 offices, staffed by approximately 5,800 salespeople. These branch employees are in close proximity to both customers and transportation providers, which gives them broad knowledge of their local markets and enables them to respond quickly to customers’ and transportation providers’ changing needs. Branch employees act as a team in their sales efforts, customer service, and operations. Approximately 32 percent of our truckload shipments are shared transactions between branches. Our branches work together to complete transactions and collectively meet the needs of our customers. For large multi-location customers, we often coordinate our efforts in one branch and rely on multiple branch locations to deliver specific geographic or modal needs. Our methodology of providing services is very similar across all branches. Our North American branches have a common technology platform that they use to match customer needs with supplier capabilities, to collaborate with other branch locations, and to utilize centralized support resources to complete all facets of the transaction. A significant portion of our branch employees’ compensation is performance-oriented, based on the profitability of their branch and their contributions to the success of the branch. We believe this makes our sales employees more service-oriented, focused, and creative.
We are a service company. We act primarily to add value and expertise in the procurement and execution of transportation and logistics, including sourcing of produce products for our customers. Our total revenues represent the total dollar value of services and goods we sell to our customers. Our net revenues are our total revenues less purchased transportation and related services, including contracted motor carrier, rail, ocean, air, and other costs, and the purchase price and services related to the products we source. Our net revenues are the primary indicator of our ability to source, add value, and sell services and products that are provided by third parties, and we consider them to be our primary performance measurement. Accordingly, the discussion of our results of operations focuses on the changes in our net revenues.
Historically, we have grown primarily through internal growth, by expanding current offices, opening new branch offices, and hiring additional salespeople. We have augmented our growth through selective acquisitions. On June 12, 2009, we acquired the operating subsidiaries of Walker Logistics Overseas, Ltd. (“Walker”). Walker was a leading international freight forwarder headquartered in London, England. Walker was a global, fully integrated import and export door-to-door provider specializing in air freight, ocean freight warehousing, courier, and logistics solutions. Its customers were primarily in electronics, telecommunications, medical, sporting goods, and military industries. The majority of their revenues were from air and ocean freight.
On July 7, 2009, we acquired certain assets of International Trade & Commerce, Inc. (“ITC”). ITC was a United States customs brokerage company specializing in warehousing, distribution, and cross-border services between the United States and Mexico. ITC was headquartered in Laredo, Texas, and had approximately 40 employees and staff. ITC provided a broad range of services facilitating customers’ international customs brokerage needs across all modes of transportation. ITC strengthened our ability to provide customers a seamless cross-border service package across the United States and Mexico border.
On September 14, 2009, we acquired certain assets of Rosemont Farms Corporation, Inc., a produce marketing company, and an affiliated company Quality Logistics, LLC (together referred to as “Rosemont”), a transportation provider that focused on produce transportation. Rosemont was headquartered in Boca Raton, Florida, and had approximately 100 employees. Rosemont offered produce and logistics solutions to retail and foodservice customers.
Multimodal Transportation and Logistics Services
C.H. Robinson provides freight transportation and related logistics and supply-chain services. Our services range from commitments on a specific shipment to much more comprehensive and integrated relationships. We execute these service commitments by hiring and training people, developing proprietary systems and technology processes, and utilizing our network of subcontracted transportation providers, including contract motor carriers, railroads, air freight carriers, and ocean carriers. We make a profit on the difference between what we charge to our customers for the totality of services provided to them and what we pay to the transportation provider to handle or transport the freight. While industry definitions vary, given our extensive subcontracting to create a flexible network of solutions, we are generally referred to in the industry as a third-party logistics company.
We provide all of the following transportation and logistics services:
•
Truckload - Through our contracts with motor carriers, we have access to dry vans, temperature controlled vans, and flatbeds. We also offer time-definite and expedited truck transportation. In many instances, we will consolidate partial shipments for several customers into full truckloads.
•
Less Than Truckload (“LTL”) - LTL transportation involves the shipment of small packages and single or multiple pallets of freight, up to and including full trailer load freight. We focus on shipments of a single pallet or larger, although we handle any size shipment. Through our contracts with motor carriers and our operating system, we consolidate freight and freight information to provide our customers with a single source of information on their freight.
•
Intermodal - Our intermodal transportation service is the shipment of freight in trailers or containers, by a combination of truck and rail. We have intermodal marketing agreements with container owners, stacktrain operators, and all Class 1 railroads in North America, and we arrange local pickup and delivery (known as drayage) through local contracted motor carriers.
•
Ocean - We consolidate shipments, determine routing, select ocean carriers, contract for ocean shipments, provide for local pickup and delivery of shipments, and arrange for customs clearance of shipments, including the payment of duties.
•
Air - We provide door-to-door service as a full-service international and domestic air freight forwarder.
•
Other Logistics Services - We provide fee-based transportation management services, customs brokerage, warehousing services, and other services.
Customers communicate their freight needs, typically on a shipment-by-shipment basis, to the branch salesperson responsible for their account. Customers communicate with us by means of telephone, fax, internet, email, or Electronic Data Interchange (EDI). The branch employee ensures that all appropriate information about each shipment is entered into our proprietary operating system. With the help of information provided by the operating system, the salesperson then selects a contracted carrier or carriers, based upon his or her knowledge of the carrier’s service capability, equipment availability, freight rates, and other relevant factors. Based on the information he or she has about the market and rates, the salesperson may either determine an appropriate price at that point or wait to communicate with a contracted carrier directly before setting a price. In
many cases, employees from different branch offices collaborate to hire the appropriate contracted carrier for our customer’s freight, and the branch offices agree to an internal profit split.
Once the contracted carrier is selected, the salesperson communicates with the contract carrier to agree on the price for the transportation and the contract carrier’s commitment to provide the transportation. We are in contact with the contract carrier through numerous means of communication (including EDI, our proprietary website CHRWTrucks® (www.chrwtrucks.com), email, fax, and telephone) to meet our customers’ requirements as well as track the status of the shipment from origin to delivery.
For most of our transportation and logistics services, we are a service provider. By accepting the customer’s order, we accept certain responsibilities for transportation of the shipment from origin to destination. The carrier’s contract is with us, not the customer, and we are responsible for prompt payment of freight charges. In the cases where we have agreed (either contractually or otherwise) to pay for claims for damage to freight while in transit, we pursue reimbursement from the contracted carrier for the claims. In our transportation management business, we are acting as a shipper’s agent. In those cases, the carrier’s contract is with the customer, and we collect a fee for our services.
As a result of our logistics capabilities, some of our customers have us handle all, or a substantial portion, of their freight transportation requirements to or from a particular manufacturing facility or distribution center. Our branch employees price our services to provide a profit to us for the totality of services performed for the customer. In some cases, our services to the customer are priced on a spot market, or transactional, basis. In a number of instances, we have contracts with the customer in which we agree to handle an estimated number of shipments usually to specified destinations, such as from the customer’s plant to a distribution center. Our commitments to handle the shipments are usually at specific rates. Most of our rate commitments are for one year or less and therefore allow for renegotiation. As is typical in the transportation industry, most of these contracts do not include specific volume commitments. When we enter into prearranged rate agreements for truckload services with our customers, we have fuel surcharge agreements in addition to the underlying line-haul portion of the rate.
The majority of our truckload freight is priced to our contract carriers on a spot market, or transactional, basis, even when we are working with the customer on a contractual basis. When we enter into spot transactions with contract motor carriers, we generally negotiate a mutually-agreed upon total market rate that includes all costs, including any applicable fuel expense. However, if requested by the contract carrier, we will estimate and report fuel separately. In a small number of cases, we may get advance commitments from one or more contract carriers to transport contracted shipments for the length of our customer contract. In those cases, where we have prearranged rates with contract carriers, there is a calculated fuel surcharge based on a mutually-agreed-upon formula.
In the course of providing day-to-day transportation services, our branch employees often identify opportunities for additional logistics services as they become more familiar with our customer’s daily operations and the nuances of its supply chain. We offer a wide range of logistics services on a worldwide basis that reduce or eliminate supply chain inefficiencies. We will analyze the customer’s current transportation rate structures, modes of shipping, and carrier selection. We can evaluate a customer’s core carrier program by establishing a program to measure and monitor key quality standards for those core carriers. We can identify opportunities to consolidate shipments for cost savings. We will suggest ways to improve operating and shipping procedures and manage claims. We can help customers minimize storage through cross-docking and other flow-through operations. We may also examine the customer’s warehousing and dock procedures. Many of these services are bundled with underlying transportation services and are not typically priced separately. They are usually included as a part of the cost of transportation services provided by us, based on the nature of the customer relationship. In addition to these transportation services, we may supply sourcing, contract warehousing, consulting, fee-based transportation management, and other services, for which we are usually paid separately.
As we have emphasized integrated logistics solutions, our relationships with many customers have broadened, and we have become key providers to our customers, responsible for helping them manage a greater portion of their supply chain. We may serve our customers through specially created teams and through several branches. Our multimodal transportation services are provided to numerous international customers through our worldwide branch network. See Note 1 in Item 8 for an allocation of our total revenues from domestic and foreign customers for the years ended December 31, 2009, 2008, and 2007 and our long-lived assets as of December 31, 2009, and 2008 in the United States and in foreign locations.
The table below shows our net revenues by transportation mode for the periods indicated:
Transportation Net Revenues
(in thousands)
(1) Includes truckload and LTL net revenues.
Transportation services accounted for approximately 88 percent of our net revenues in 2009, 2008, and 2007.
Sourcing
Since we were founded in 1905, we have been in the business of sourcing fresh produce. Much of our logistics expertise can be traced to our significant experience in handling produce and other perishable commodities. Because of its perishable nature, produce must be rapidly packaged, carefully transported within tight timetables usually in temperature controlled equipment, and quickly distributed to replenish high-turnover inventories maintained by retailers, wholesalers, foodservice companies, and restaurants. In many instances, we consolidate individual customers’ produce orders into truckload quantities at the point of origin and arrange for transportation of the truckloads, often to multiple destinations.
For several years, we have actively sought to expand our Sourcing customer base by focusing on large multistore grocery retailers, restaurant chains, and foodservice providers. Historically, grocery retailers have relied primarily on regional or even local purchases from food wholesalers for produce sourcing and store-level distribution. As these retailers have expanded through store openings and industry consolidation, these methods have become inefficient. Our logistics and perishable commodities sourcing expertise can improve the retailers’ produce purchasing and provide consistent quality across regions and stores.
Our Sourcing services have expanded to include just-in-time replenishment, commodity management, and business analysis. We have various national and regional branded produce programs, including both proprietary brands and national licensed brands. These programs contain a wide variety of fresh bulk and value added fruits and vegetables that are high in quality. These brands have expanded our market presence and relationships with many of our retail customers. We have also instituted quality assurance and monitoring programs as part of our branded and preferred supplier programs.
Sourcing accounted for approximately nine percent of our net revenues in 2009 and eight percent in 2008 and 2007.
Information Services
T-Chek’s customers are primarily motor carriers and truck stop chains. T-Chek provides its customers with fuel management services, funds transfer, spend management reporting, driver payroll services, permits, and online access to customized business intelligence, all through the use of its proprietary automated systems. These systems enable customers to track and manage certain expenses, including fuel and maintenance. For several companies and truck stop chains, T-Chek captures sales and fuel cost data, provides management information to the seller, and invoices the carrier for fuel, cash advances, and our fee.
Information Services accounted for approximately three percent of our net revenues in 2009 and four percent in 2008 and 2007.
Organization
To keep us close to our customers and markets, we operate through a network of offices, which we call “branches.” We currently have 235 branches, up from 228 in 2008. Our branches are supported by our corporate executives and other centralized, shared services. Approximately 13 percent of our employees are corporate employees who provide these

# Financial QA 

https://huggingface.co/datasets/virattt/financial-qa-10K

In [57]:
from datasets import load_dataset

ds = load_dataset("virattt/financial-qa-10K")

README.md:   0%|          | 0.00/419 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7000 [00:00<?, ? examples/s]

In [58]:
ds

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'context', 'ticker', 'filing'],
        num_rows: 7000
    })
})

In [59]:
df2 = ds["train"].to_pandas()

In [60]:
df2.head()

,question,answer,context,ticker,filing
0,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,"Since our original focus on PC graphics, we ha...",NVDA,2023_10K
1,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Some of the most recent applications of GPU-po...,NVDA,2023_10K
2,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,Our invention of the GPU in 1999 defined moder...,NVDA,2023_10K
3,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"NVIDIA has a platform strategy, bringing toget...",NVDA,2023_10K
4,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,With our introduction of the CUDA programming ...,NVDA,2023_10K

In [62]:
df2.question[0]

'What area did NVIDIA initially focus on before expanding to other computationally intensive fields?'

In [63]:
df2.answer[0]

'NVIDIA initially focused on PC graphics.'

In [64]:
df2.context[0]

'Since our original focus on PC graphics, we have expanded to several other large and important computationally intensive fields.'

In [67]:
df2.filing.unique()

<ArrowStringArray>
['2023_10K']
Length: 1, dtype: str