In [1]:
import pandas as pd

df = pd.read_parquet("hf://datasets/FinGPT/fingpt-fiqa_qa/data/train-00000-of-00001-ab79bf9300210e98.parquet")

In [2]:
df.columns

Index(['input', 'output', 'instruction'], dtype='str')

In [17]:
df.shape

(17110, 3)

In [3]:
df.head()

,input,output,instruction
0,What is considered a business expense on a bus...,The IRS Guidance pertaining to the subject. I...,"Utilize your financial knowledge, give your an..."
1,Claiming business expenses for a business with...,Yes you can claim your business deductions if ...,Offer your insights or judgment on the input f...
2,Transferring money from One business checking ...,You should have separate files for each of the...,"Based on your financial expertise, provide you..."
3,Having a separate bank account for business/in...,Having a separate checking account for the bus...,Share your insights or perspective on the fina...
4,Having a separate bank account for business/in...,"You don't specify which country you are in, so...",Offer your thoughts or opinion on the input fi...

## Samples

In [13]:
index = 0
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  What is considered a business expense on a business trip?
output:  The IRS Guidance pertaining to the subject.  In general the best I can say is your business expense may be deductible.  But it depends on the circumstances and what it is you want to deduct. Travel Taxpayers who travel away from home on business may deduct related   expenses, including the cost of reaching their destination, the cost   of lodging and meals and other ordinary and necessary expenses.   Taxpayers are considered “traveling away from home” if their duties   require them to be away from home substantially longer than an   ordinary day’s work and they need to sleep or rest to meet the demands   of their work. The actual cost of meals and incidental expenses may be   deducted or the taxpayer may use a standard meal allowance and reduced   record keeping requirements. Regardless of the method used, meal   deductions are generally limited to 50 percent as stated earlier.    Only actual costs for lodging may be claimed as an expense and   receipts must be kept for documentation. Expenses must be reasonable   and appropriate; deductions for extravagant expenses are not   allowable. More information is available in Publication 463, Travel,   Entertainment, Gift, and Car Expenses. Entertainment Expenses for entertaining clients, customers or employees may be   deducted if they are both ordinary and necessary and meet one of the   following tests: Directly-related test: The main purpose of the entertainment activity is the conduct of business, business was actually conducted   during the activity and the taxpayer had more than a general   expectation of getting income or some other specific business benefit   at some future time.   Associated test: The entertainment was associated with the active conduct of the taxpayer’s trade or business and occurred directly   before or after a substantial business discussion. Publication 463 provides more extensive explanation of these tests as   well as other limitations and requirements for deducting entertainment   expenses. Gifts Taxpayers may deduct some or all of the cost of gifts given in the   course of their trade or business. In general, the deduction is   limited to $25 for gifts given directly or indirectly to any one   person during the tax year. More discussion of the rules and   limitations can be found in Publication 463. If your LLC reimburses you for expenses outside of this guidance it should be treated as Income for tax purposes. Edit for Meal Expenses: Amount of standard meal allowance.   The standard meal allowance is   the federal M&IE rate. For travel in 2010, the rate for most small   localities in the United States is $46 a day. Source IRS P463 Alternately you could reimburse at a per diem rate
instruction:  Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.

In [16]:
index = 1
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  Claiming business expenses for a business with no income
output:  Yes you can claim your business deductions if you are not making any income yet. But first you should decide what structure you want to have for your business. Either a Company structure or a Sole Trader or Partnership. Company Structure If you choose a Company Structure (which is more expensive to set up) you would claim your deductions but no income. So you would be making a loss, and continue making losses until your income from the business exceed your expenses. So these losses will remain inside the Company and can be carried forward to future income years when you are making profits to offset these profits. Refer to ATO - Company tax losses for more information. Sole Trader of Partnership Structure If you choose to be a Sole Trader or a Partnership and your business makes a loss you must check the non-commercial loss rules to see if you can offset the loss against your income from other sources, such as wages. In order to offset your business losses against your other income your business must  pass one of these tests: If you don't pass any of these tests, which being a start-up you most likely won't, you must carry forward your business losses until an income year in which you do pass one of the tests, then you can offset it against your other income. This is what differentiates a legitimate business from someone having a hobby, because unless you start making at least $20,000 in sales income (the easiest test to pass) you cannot use your business losses against your other income. Refer to ATO - Non-commercial losses for more information.
instruction:  Offer your insights or judgment on the input financial query or topic using your financial expertise. Reply as normal question answering

In [14]:
index = 100
print("input: ", df["input"][index])
print("output: ", df["output"][index])
print("instruction: ", df["instruction"][index])

input:  How can I lookup the business associated with a FEIN?
output:  If the organization is a non-profit. You can search by EIN on Charity Navigator's website FOR FREE. https://www.charitynavigator.org/
instruction:  Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.

## Missing data?

In [18]:
df.describe()

,input,output,instruction
count,17110,17110,17110
unique,6648,17071,5
top,"What options do I have at 26 years old, with 1...",nan,"Utilize your financial knowledge, give your an..."
freq,23,38,3422

There are 5 types of instructions:

In [23]:
for i, prompt in enumerate(df.instruction.unique()):
    print(f"Prompt {i}:", prompt, "\n\n")

Prompt 0: Utilize your financial knowledge, give your answer or opinion to the input question or subject . Answer format is not limited.


Prompt 1: Offer your insights or judgment on the input financial query or topic using your financial expertise. Reply as normal question answering


Prompt 2: Based on your financial expertise, provide your response or viewpoint on the given financial question or topic. The response format is open.


Prompt 3: Share your insights or perspective on the financial matter presented in the input.


Prompt 4: Offer your thoughts or opinion on the input financial query or topic using your financial background.